### ISSUE TITLE
Page article : Ajout EAN et Ref

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#1]
![page article v11](https://cloud.githubusercontent.com/assets/12218448/7444455/19c46e02-f184-11e4-98fc-b450c31f1a16.png)

J'ai aussi modifié le texte de la participation au vote : J'ai essayé cet article..... Les gens ayant essayé meme sans acheté peuvent aussi donner leur avis.

**Comment by wilsto** [comment]
Ok, c'est corrigé version 0.2.6
