### ISSUE TITLE
bandeau  "la perf...."

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#12]
![la_performance_en_toute_transparence_avec _etoiles](https://cloud.githubusercontent.com/assets/12218448/7539793/b7b389a8-f5a9-11e4-8b11-ee2df4c8dfc5.jpg)

**Comment by nepco15** [comment]
Il faut centrer avec le logo par rapport aux étoiles et non la phrase.

**Comment by nepco15** [comment]
Il faut centrer les étoiles sous le Performance du logo.

![visuel site web v5 20150508](https://cloud.githubusercontent.com/assets/12218448/7540038/b69f4e60-f5ab-11e4-8030-ffca89bc8642.jpg)
visuel V5 (désolée...) j'ai dormi 7h d'affilées mon cerveau est en fusion !

**Comment by nepco15** [comment]
J'ai passé un moment pour les espaces entres le logo la phrase et la ligne ainsi que la barre de menu... si tu arrives à coller au max à ca ce serait top. 
Pour la barre de recherche on peut la descendre un peu...

**Comment by wilsto** [comment]
les étoiles sont centrées sous le mot performance
la phrase est collée au maximum

**Comment by nepco15** [comment]
re, la phrase n’apparaît
![site web vue actuelle 20150509 13h04](https://cloud.githubusercontent.com/assets/12218448/7549940/9cca8396-f64c-11e4-8e3d-5863397fb000.jpg)
 pas sur ma version du site.
Petit erratum, par coller à ca, je parlais respecter les espaces que j'avais mis dans l'exemple. Donc justement pas trop collé au logo ni à la barre/
Je te mets un visuel de ce qui s'affiche chez moi.

**Comment by wilsto** [comment]
![image](https://cloud.githubusercontent.com/assets/4889715/7550071/89be5ca8-f653-11e4-8cd5-5a6c1c8f50f0.png)
Nouvelle version, réouvre l'issue si ce n'est pas ce que tu attends
