### ISSUE TITLE
Police générale : Bell MT

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#15]
Si c'est possible

**Comment by wilsto** [comment]
Bell MT n'est pas une font Web, la plus proche que j'ai trouvé est Cardo
https://www.google.com/fonts/specimen/Cardo
et les performances de chargement sont bons 
https://www.google.com/fonts#QuickUsePlace:quickUse

si tu veux en changer dis le moi: y'a 683 font ici 
https://www.google.com/fonts
