### ISSUE TITLE
Les derniers arrivés : Encart => + Marque / + graph. / - descrip 

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#2]
Sur l'encart qui défile, supprimer également le descriptif. 
En revanche ajouter la marque en majuscule au dessus de la dénomination.
Et si possible d'ajouter le graph avec un rendu visuel bien, ca peut etre pas mal.

**Comment by wilsto** [comment]
descriptif supprimé
marque au dessu en majuscule
la troisième demande est plus compliquée
je ferme cette demande et en ouvre une spécifique
