### ISSUE TITLE
fiche article : Les 5 étoiles => OR

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#21]
Est-ce possible de mettre les étoiles en OR comme le logo ?

**Comment by wilsto** [comment]
![image](https://cloud.githubusercontent.com/assets/4889715/7549839/fd7efa5e-f648-11e4-83df-3315e28331da.png)

**Comment by wilsto** [comment]
![image](https://cloud.githubusercontent.com/assets/4889715/7549843/38c4d386-f649-11e4-8fbf-c07f5f7628e8.png)
Meme chose coté article
