### ISSUE TITLE
Fiche article : Ajouter espaces dans le bandeau supérieur

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#23]
Espacer un peu entre la marque et la designation ainsi qu'entre la désignation et l'EAN et Ref

**Comment by wilsto** [comment]
avant
![image](https://cloud.githubusercontent.com/assets/4889715/7550123/dc22a6a0-f655-11e4-8d20-ca78e4b24b8b.png)

après
![image](https://cloud.githubusercontent.com/assets/4889715/7550127/1729dd4a-f656-11e4-9c80-7c16cf7c054d.png)

**Comment by wilsto** [comment]
Si l'espace est top grand/petit dis le moi
