### ISSUE TITLE
Fiche Article : Profil Performance : PLUS GROS

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#26]
Peut-on grossir  le profil ?

**Comment by nepco15** [comment]
Il faut que l'oeil soit plus attiré par le profil que par la photo.... peut etre que ca passe aussi par une diminution de la photo... (?)

**Comment by wilsto** [comment]
avant
![image](https://cloud.githubusercontent.com/assets/4889715/7550159/b3775122-f657-11e4-8ff8-3be049958f56.png)

après
![image](https://cloud.githubusercontent.com/assets/4889715/7550162/be279514-f657-11e4-9d8e-082a058b7939.png)
