### ISSUE TITLE
Fiche Article : Les titres : Petites majuscules et soulignés

### ISSUE THREAD

**Issue by nepco15** [wilsto/nepco#27]
Il faudrait qu'on voit mieux les titres pour mieux comprendre comment s'organise cette fiche.
On essaie avec les petites majuscules et le soulignement...  on grossira éventuellement ou on ajoutera une ombre si ca ne suffit pas....

**Comment by wilsto** [comment]
![image](https://cloud.githubusercontent.com/assets/4889715/7550239/4772d4ee-f65a-11e4-9ee0-9902a93549fa.png)

**Comment by wilsto** [comment]
n'hésites pas à réouvrir si ce n'est pas ce que tu attendais

**Comment by nepco15** [comment]
ca me semble bien. n,'hesite pas si tu trouves que c'est moins bien !!!!
